### PR TITLE
create initial backend project

### LINKED ISSUE #2: Backend initial project setup
ASP.net core Minimal API

### PR DESCRIPTION
**Pull request by mahedee**
Create an initial backend project to start working. We will refactor code latter on. If you find anything wrong, create an issue for that.

### CODE REVIEW

**Review by cseshohag — COMMENTED** [review]
Looks everything is ok. But i did not find the minimal api configuration.

**Comment by ratanparai** [comment]
@mahedee bhai is there any specific reason to change the plan to use minimal API as described in #2 ?

**Comment by mahedee** [comment]
> @mahedee bhai is there any specific reason to change the plan to use minimal API as described in #2 ?

@ratanparai,  if understand correctly, minimal API is in the controller level, right? So, when we will create any controller, we will choose a minimal api. Is it ok?

**Comment by ratanparai** [comment]
@mahedee Please check https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio

**Comment by mahedee** [comment]
I am closing this pull request and creating a new one with updated setup

**Comment by mahedee** [comment]
I am closing this pull request and creating another PR with updated setup

**Pull request closed without merging**
